### ISSUE TITLE
GitHub Actions Not Updating Dashrep.Org Web Page?

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#18]
[comment]: # (https://github.com/cpsolver/Dashrep-language/issues/14)

Hi Richard (@cpsolver),

### Update of Specifications HTML Documentation

Thank you for updating the [output_specifications_documentation.html](https://github.com/cpsolver/Dashrep-language/blob/master/output_specifications_documentation.html) file in commit  https://github.com/cpsolver/Dashrep-language/commit/55b832e687fc8e482b4961bb619845b4ad16be37. Using the GitHub HTML Preview utility on the "[raw](https://raw.githubusercontent.com/cpsolver/Dashrep-language/master/output_specifications_documentation.html)" version of the file, shows that the [resulting web page](https://htmlpreview.github.io/?https://raw.githubusercontent.com/cpsolver/Dashrep-language/master/output_specifications_documentation.html) now looks much better with all the recent changes included.

### Update of Dashrep.Org website HTML

However, even though this specific HTML file has been updated correctly, it does not look like the HTML for the Dashrep.Org website itself has been updated correspondingly. I looked at the "Build and Deploy" background processing that GitHub renders for the repo. For example, the [Actions](https://github.com/cpsolver/Dashrep-language/actions) page shows the runs from all the workflows triggered from the various updates to the repo going back to Jul 9th, 2023.

### GitHub Actions setup

I am not familiar with how GitHub Actions are set up in the Dashrep-language repo, but I have contributed in the past to the [Programming Language Database (PLDB)](https://github.com/breck7/pldb) repo which has its own "[.github/workflows](https://github.com/breck7/pldb/tree/main/.github/workflows)" folder, which is typical of most repos.  But upon further investigation, it seems that **".github/workflows"** is for custom workflows and that instead both repos have what appears to be a default workflow called _pages-build-deployment_. I am guessing that for the Dashrep repo, these are all setup using the Settings option for the repo, to which only you would have access.

### Default GitHub Action for GitHub Pages Deployment

When I look at the [pages-build-deployment](https://github.com/cpsolver/Dashrep-language/actions/workflows/pages/pages-build-deployment) workflows, and check [#24](https://github.com/cpsolver/Dashrep-language/actions/runs/10517929326) (for the commit mentioned above), I see at the bottom of the page that there is a single artifact created called "github-pages" (size 44.2kb). According to [this page](https://github.com/actions/upload-pages-artifact?tab=readme-ov-file#artifact-validation), the artifact is a gzip archive which contains a single "tar" file (Unix "tarball" archiving format). Since I am on Windows, 7-Zip handles both formats without a problem.

When I download the zip file, these the contents of the inner "tar" file:

![Contents-of-tar-file](https://github.com/user-attachments/assets/9b8c1e3c-d032-4e61-906f-f9735875871a)

So, to check if these files were deployed to the website, I took the following steps:

### Website Page Comparison

I downloaded the Dashrep.Org website using Cyotek WebCopy and checked the Meta information for the Last Modified Date:

![Website-Last-Modified-Date](https://github.com/user-attachments/assets/a9cd169b-01ac-4cb3-92d7-833ac560a088)

It would appear that the website has not been updated since early May of this year (that is, if the Modified Date is correct). The website download only contained a single "[index.html](https://dashrep.org/index.html)" file, as expected.

Interestingly, the "index.html" file from both the website and the GitHub artifact are _*identical*_ down to the same UTF-8 encoding and Unix (LF) line endings.

The "assets" folder in the GitHub artifact contains a "css" folder, in which is a single "style.css" file. This looks to be generated by GitHub as seen from the first line in the file:

![GitHub-style-css](https://github.com/user-attachments/assets/718ae130-07c7-4bf1-95c4-dc05f4cca595)

It certainly has not been deployed to the website, since https://dashrep.org/assets/css/style.css is generating a 404 error.

Since the "index.html" files are identical, my guess is that at a point in the past, the files were manually synced as there is no "Build and Deploy" background processing from beyond two weeks ago. There is, however, ONE deployment from last year, but this generated an artifact that was 230Kb (very much larger than the recent deployments), but it cannot be examined as it has [expired](https://github.com/cpsolver/Dashrep-language/actions/runs/5497788067).

### Something To Check

It would appear that the Jekyll website build is not generating anything new on each update, and it is also not deploying to the website correctly. The "[Build with Jekyll](https://github.com/cpsolver/Dashrep-language/actions/runs/10517929326/job/29142919829#step:4:42)" portion of the build is generating the `/assets/css/style.css` file, but I do not see where the "index.html" is being generated.

I am not familiar with creating a Jekyll website using GitHub Actions, so I cannot troubleshoot this any further until I learn more about the process myself. In any case, this is something worth looking into in the future as it would be important that not only the repo files themselves should be updated, but all the applicable updates should also be reflected on the actual website itself.

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
[comment]: # (https://github.com/cpsolver/Dashrep-language/issues/18)

Hi Richard (@cpsolver),

By accident, I just stumbled on the [docs](https://github.com/cpsolver/Dashrep-language/tree/master/docs) folder in the repo where I found both the "index.html" (last updated in https://github.com/cpsolver/Dashrep-language/commit/14368077be3395f4cc2b72a2ebd25d1e5e12f610 on Jul 9, 2023) and the "sitemap_dr.xml" file (last updated in https://github.com/cpsolver/Dashrep-language/commit/9659ecd7c17bacc855abc87bd4bde08c5a140647 on Nov 11, 2022).

Well, that at least explains the deployment on Jul 9th, 2023. I'm guessing that there is a separate process that updates this "index.html" file.

I see that you used to once have a "[dashrep_dot_org_website](https://github.com/cpsolver/Dashrep-language/tree/9db4f54442947e186dbbc7fcd9059b52739d15a2/dashrep_dot_org_website)" folder in which these two files resided, before you created the "docs" folder. So, part of the mystery is solved. 

In any case, this is all part of learning more about the Dashrep language and its associated website! 😄

Kind Regards,
Liam

**Comment by cpsolver** [comment]
Liam, I apologize for not having properly documented this process.

I manually copy and paste from the output_specifications_documentation.html file here to the index.html file on the hosted website.

I do it this way because I haven't been able to figure out how to point the Dashrep.org domain name to an HTML file here at Github.  If you know how to do this, please let me know.

I have looked at "GitHub Actions" and I like the general idea, but I don't like its limitations.  It's easier to generate needed files locally.

I briefly looked at the Jekyll website platform but it does not seem well-designed for my needs here.  (I don't even need the ability to refer to a stylesheet.css file because I can embed the CSS code within the single HTML file.)  I just need to be able to link the domain name to the HTML file.

My next task is to do the manual update of the index.html file ... now that I've learned how to "pull" your documentation refinements and "fetch" and "merge" them into my local repository.

I'll leave this open in case you discover mistakes after I manually copy and paste the updated documentation.

**Comment by cpsolver** [comment]
I just updated the index.html file at Dashrep.org by pasting into that file the updated phrase descriptions copied from the output_specifications_documentation.html file here.  Again, thank you Liam for your valuable help!!  Let me know if you find any more documentation mistakes.

**Comment by cpsolver** [comment]
I'm closing this issue because apparently there is no way to point the Dashrep.org domain name to an HTML file here on Github.

The webpage at Dashrep.org must be updated manually, not through any automation available on GitHub or in the domain name settings.

Clarifications: Yes it's possible to create a URL link to an HTML file on GithHub, but the domain name cannot use that link as a target.  As indicated in the comments for this issue, the Jekyll option does not work with a webpage that already gets generated using the Dashrep compiler.
