### ISSUE TITLE
Highlighting Actions in Sublime Text

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#19]
[comment]: # (https://github.com/cpsolver/Dashrep-language/issue/19)

Hi Richard (@cpsolver),

While searching through the [dashrep_compiler_source_code.txt](https://github.com/cpsolver/Dashrep-language/blob/40f75ff8ce58736f53fd86abcc73130609d80db5/dashrep_compiler_source_code.txt#L3384-L3386) for the string "**required-operand-count-for-action-**", I noticed a slight inconsistency in how Sublime Text flagged the "action" portion following the string. 

**Note**: In the examples below, I am using "Quick Search" (\<Alt>\<F3>) to highlight the search string.

Most the "action" phrases are marked with an _italic type font_:

![italic_font_for_actions](https://github.com/user-attachments/assets/d7879ef4-3d4b-4e64-9e03-01d552f227de)

However, in a few cases, they are marked in cyan blue:

![cyan_marked_font_for_actions](https://github.com/user-attachments/assets/f9da66c8-37fc-40df-a8f2-9a14b545c3e5)

There are 117 actions in total, of which the following 26 phrases are not marked the same as the other actions in the list. I have given below the description of the "exception" phrases from the [Dashrep.Org](https://dashrep.org/) website.

The 26 affected phrases are:

| **Phrase**                                  | **Description** |
|---------------------------------------------|:---------------:|
| get-characters-from-position-to-position    |      action     |
| get-count-of-characters                     |      action     |
| get-count-of-words                          |      action     |
| get-current-time-in-epoch-seconds           |      action     |
| get-position-of-matching-text               |      action     |
| get-position-of-word                        |      action     |
| get-word-at-position                        |      action     |
| modification-time-of-file                   |      action     |
| numeric-absolute                            |      action     |
| numeric-cosine                              |      action     |
| numeric-divide-by                           |      action     |
| numeric-equal-greater-less-compare          |      action     |
| numeric-integer                             |      action     |
| numeric-logarithm-base-10                   |      action     |
| numeric-logarithm-base-e                    |      action     |
| numeric-minus                               |      action     |
| numeric-odd-or-even                         |      action     |
| numeric-sine                                |      action     |
| numeric-square-root                         |      action     |
| numeric-y-map-tile-number-based-on-latitude |      action     |
| yes-or-no-empty-phrase                      |      action     |
| yes-or-no-file-exists                       |      action     |
| yes-or-no-folder-exists                     |      action     |
| yes-or-no-same-two-phrase-definitions       |      action     |
| zero-one-multiple                           |      action     |
| zero-or-nonzero                             |      action     |

They are, expectedly, all consistently described as an action. I will therefore make a PR to change the syntax highlighting in Sublime Text to reflect that fact.

Kind Regards,
Liam

**Comment by celtic-coder** [comment]
In my testing, I found that I had missed "size-of-file" from the list above. Since it is an action, I will amend the PR to take account of this phrase.

**Comment by cpsolver** [comment]
In another place, "Update Sublime highlighting for selected actions #20," I requested moving a few more actions into the correct font style.  (I'm still learning how to use GitHub.  In hindsight I probably should have written that comment here.)

**Comment by celtic-coder** [comment]
Hi Richard (@cpsolver),

That's not a problem! I will work on the list that you mentioned in https://github.com/cpsolver/Dashrep-language/pull/20#pullrequestreview-2267413834. I will not be able to do so for the next few days as I will be away from my computer. But I will get to it as soon as possible following my return.

Kind Regards,
Liam

**Comment by cpsolver** [comment]
Again, thank you Liam!  I've merged your changes so I'm closing this issue.
