### ISSUE TITLE
Square bracket character descriptions

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#4]
Hi Richard (@cpsolver),

On the [Dashrep.org](http://www.dashrep.org/) website under the section **"Hyphens, spaces, lines, & special characters"** are the descriptions for the following three phrases:

- character-newline
- character-open-square-bracket
- character-close-square-bracket

They appear as follows:

![square-bracket-descriptions](https://user-images.githubusercontent.com/11787866/163891950-5e2ca6b7-3b27-4fc3-954d-b2fabc51c41e.png)

As can be seen both the _open square bracket_ and the _close square bracket_ descriptions are the same as the one for _newline_.

However, at this point I am puzzled. 

I can find the definition of [description-for-phrase-character-newline:](https://github.com/cpsolver/Dashrep-language/blob/master/specifications_phrase_descriptions.txt#L120-L125) in **specifications_phrase_descriptions.txt** on GitHub at:

![description-for-phrase-character-newline](https://user-images.githubusercontent.com/11787866/163893480-0af093e9-6cf2-4c66-8635-7ca7706bdc25.png)

But I cannot find any descriptions about *open-square-bracket* or *close-square-bracket* in that file. 

I can find the three phrases in the [output_specifications_documentation.html](https://github.com/cpsolver/Dashrep-language/blob/master/output_specifications_documentation.html) on GitHub, which seems to be repeated on the website.

Are the two duplicate _square bracket_ descriptions generated elsewhere? Does the incorporation of this specific content,  both on the website and in the **output_specifications_documentation.html** file, require investigation?

Kind Regards,
Liam

**Comment by cpsolver** [comment]
@celtic-coder , Thank you for finding this documentation error!  The source-code documentation files and the Dashrep.org webpage are now fixed.  Those two phrases were created to accommodate an earlier syntax that involved square brackets.  Internally the compiler still recognizes these two character phrases, but eventually they will be removed, so I removed them from the documentation.  I also fixed a few other minor documentation issues. Again, thank you!!
