### ISSUE TITLE
Suggested topics for Dashrep-related repos

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#5]
Hi Richard (@cpsolver),

I noticed that you do not have any [topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) associated with the Dashrep repository. Here are some suggested topics that you might use to classify the repo and make it easier to find on GitHub:

| **Topic**                                                            | **Number of Repos** |
|----------------------------------------------------------------------|--------------------:|
| [text-manipulation](https://github.com/topics/text-manipulation)     |          39         |
| [text-formatting](https://github.com/topics/text-formatting)         |          63         |
| [template-language](https://github.com/topics/template-language)     |         125         |
| [string-manipulation](https://github.com/topics/string-manipulation) |         902         |
| [text-processing](https://github.com/topics/text-processing)         |        1084         |

**Note**: You can also create your own "dashrep" topic and possibly add the topic to the following repos:

- [Dashrep-language](https://github.com/cpsolver/Dashrep-language)
- [Vote-Info-Split-Join-VISJ](https://github.com/cpsolver/Vote-Info-Split-Join-VISJ)
- [VoteFair-polls](https://github.com/cpsolver/VoteFair-polls)
- [VoteFair-ranking](https://github.com/cpsolver/VoteFair-ranking)

This way GitHub users will find that all Dashrep related repositories are now grouped together for easier browsing.

Kind Regards,
Liam

**Comment by cpsolver** [comment]
Thank you Liam (@celtic-coder)!  I just added the topics you suggested.  Currently all the up-to-date Dashrep code is in the Dashrep-language repository, so it's the only repository with the new "Dashrep" topic.  I'm assuming this allows anyone else who writes Dashrep code to associate their code with the Dashrep compiler repository.  Thank you for taking the time to help out with this project! Best regards, Richard

**Comment by celtic-coder** [comment]
Hi Richard (@cpsolver),

You can also add your own three VoteFair-related repos, that I mentioned above, to the Dashrep topic. Since they include Dashrep code they are fair candidates.

If you have any other repos that are like that (which I might have missed), they could also be included.

Kind Regards,
Liam

**Comment by cpsolver** [comment]
Liam (@celtic-coder), thanks for the suggestion.  I don't want to associate the VoteFair software with the Dashrep language even though they can be used together.  In a sense, the whole point is to split the numeric vote-counting software from the text-manipulation software, and that also can be done using other text-manipulation software. Also, that Dashrep code uses a former syntax, which I don't want to call attention to.

BTW, a big advantage to the Dashrep language not having been used by anyone else while developing it was that I was free to improve the language without much concern about backward compatibility.  That contrasts with Javascript which was (I read) created in a couple of weeks, which makes it difficult to change.
