### ISSUE TITLE
Links and Content on Dashrep.org

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#6]
Hi Richard (@cpsolver),

As I was checking out the Dashrep web page, I noticed some things regarding both the links and the content, that might need to be changed. These are just observations. Feel free to ignore as you see fit! :)

### Missing Links

A web search shows the following pages as belonging to the **dashrep.org** website:

- http://www.dashrep.org/learn.html
- http://www.dashrep.org/demo.html
- http://www.dashrep.org/specifications.html (which [redirects](https://wheregoes.com/trace/20222157911/) to http://www.dashrep.org/)
- http://www.dashrep.org/downloads.html
- http://www.dashrep.org/convert.html
- http://www.dashrep.org/discussion.html

However, none of these pages are linked from the Home page. Is this intentional, as they contain older versions of the Dashrep code? Might some of them be upgraded at some stage in the future? The **demo**, for example, is quite useful and might be helpful for a beginner to experiment with the code.

Alternatively, if you do not want these pages to be found in the search engines, then you might want to consider deleting them from the site.

### The Language Description

The Meta Description for the page says: _"The Dashrep programming language is simple, powerful, and fast"._ Is this the key idea that you want to have associated with the language? These three key points are also found at the top of the web page.

Maybe the description or the key points could be improved?

The [Fledging Languages](https://fll.presidentbeef.com/lang/dashrep) description for Dashrep says: _"A text-manipulation programming language that saves coding time and debugging time."_

Perhaps this description and the current one on the webpage could be combined to highlight the key feature of the language?

Could the following (also from the Fledging Languages page) be included?

_Dashrep translation replaces English-like hyphenated phrases, such as outline–attention–begin, with any text you define for those phrases._

_Special hyphenated phrases allow you to specify complex results—including lists, lists within lists, and branching—in a modular, easy-to-debug, way._

These details are from 2015. You may have a more current summary in mind or other details that you want to emphasize. Perhaps you might want to include some points from the [GitHub repository](https://github.com/cpsolver/Dashrep-language) description?

*Dashrep is a versatile descriptive programming language based on hyphenated phrases being successively expanded into replacement text. It is a much more flexible alternative to using a template language.*

In any case, you might consider adjusting the description of the language on the main page to be more than just "simple, powerful, and fast". Its unique features should catch the attention of the reader.

### Definition of a Comment

In the section **Debugging-support phrases**, there is the description of `dashrep-comments-ignored`:

_This phrase contains text that the translation process has identified as comments.  Comments are contained within the text \*--- and ---\*, but these delimiters cannot be nested, so this definition can be useful for debugging._

The definition of a comment as `*--- <<comment>> ---*` is tested in the [test-of-comment-delimiters.txt](https://github.com/cpsolver/Dashrep-language/blob/master/test_dashrep_code/test-of-comment-delimiters.txt) file as:

~~~
beginning text
*---- comment text ----*
middle text
*--- comment text ---*
ending text
~~~

Is the "star and three dashes" designed for a single-line comment and the **combee** and **comenn** designed for multiple-line comments? The "star and three dashes" variant is not defined as a comment anywhere on the main page. Is this because it will be deprecated at some time in the future? If not, should it be defined as an allowed syntax?

### Keywords or "key words"?

Under the initial sample code is the sentence: _(Many powerful actions, which are described below, can be used directly after the key words ambee and fenambee.)_

Beneath this is the heading: _The Dashrep language uses these special key words:_

In programming languages, my understanding is that "keywords" is the preferred usage.

### \<title\> and \<h1\> tags

In the \<head\>...\</head\> portion of the webpage, there is no \<title\>...\</title\> tag. The Title tag is important for SEO as that is what appears in the search results and in the browser tab. Keep it less than the recommended maximum of 65 characters and you should be fine.

A suggested Title might be: **Dashrep - The powerful text-manipulation programming language**.

Technically, there should only be one \<h1\> tag on a page. It should refer to the key topic. You have 4, but that is not a big deal. Changing the \<h1\> tags might mean changing the \<h2\> tags, and so on. The effort is not worth it especially as the bulk of these tags are auto generated.

### Summary

These are just suggestions, Richard. Feel free to take them on board or ignore as you see fit! :)

Kind Regards,
Liam

**Comment by cpsolver** [comment]
Liam (@celtic-coder), I've implemented most of your corrections and suggestions. Thank you!

There are still 3 <h1> tags, but hopefully search engines know enough to use the first instance. I don't have time to deal with the CSS changes that would be required as a result of changing the tag levels.

I don't have time to update the Fledgling Languages description.  It's been there for years and hasn't seemed to initiate any interest in the Dashrep language.

If you see any more needed corrections, please tell me.  Liam, your suggestions have been excellent!
