### ISSUE TITLE
SSL certificate expired on newsherenow.com

### ISSUE THREAD

**Issue by celtic-coder** [cpsolver/Dashrep-language#7]
Hi Richard (@cpsolver),

The SSL Certificate for https://www.newsherenow.com/ has expired as per this [Qualys SSL Labs report](https://www.ssllabs.com/ssltest/analyze.html?d=www.newsherenow.com&hideResults=on). The certificate expired on 1st July 2024 (14 days ago).

Kind Regards,
Liam

**Comment by cpsolver** [comment]
The NewsHereNow.com website has been partially migrated to a new web hosting package that includes an SSL certificate.  HTTPS access is back to working.

**Comment by celtic-coder** [comment]
Hi Richard (@cpsolver),

I can confirm that the SSL certificate for the website is getting an *A* rating and everything looks OK. I'll close this issue.

Kind Regards,
Liam
